# MUST EDIT BELOW
sitename: Connor McSheffrey Codes       #Your site title
tagline: My coding sandbox  #You should always have a tagline
url: http://code.connormcsheffrey.com   #URL Please
ga: UA-XXXXX-X              #Google Analytics ID
sitemap: GOOGLEWEBMASTER    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile
